### ISSUE TITLE
Documentation update: gnome terminal isn't detected, works fine

### ISSUE THREAD

**Issue by evaryont** [drmikehenry/vim-fixkey#6] opened 2016-09-20 22:36 UTC
I'm running gnome-terminal 3.20.2 at the moment, and the following key bindings work:

```vim
" A few dumb key bindings to test if the terminal I'm using supports a full
" variety of extra modifiers
map <M-u> :echo 'hi'<CR>
map <M-U> :echo 'bye'<CR>
map <C-u> :echo 'controlled response'<CR>
map <M-Enter> :echo 'alternate confirm'<CR>
map <M-C-S-Enter> :echo 'why would you ever do this to me'<CR>
map <S-Home> :echo 'early riser'<CR>
map <C-End> :echo 'night owl'<CR>
map <S-F1> :echo 'big question'<CR>
map <C-F1> :echo 'questioning question'<CR>
map <S-C-F1> :echo 'questing knight'<CR>
map <S-M-F1> :echo 'magical girl function key!'<CR>
map <C-S-M-F1> :echo 'there be dragons here'<CR>
map <C-S-M-Down> :echo "don't look at me"<CR>
```

I'm not sure since when this has been the case, but `$COLORTERM` is set to "truecolor", and `g:Fixkey_termType` is set to "xterm".

A really odd behaviour I just found out about is with Shift-Enter. Normal shift + enter doesn't work, however if I press the function key and enter on my laptop, it sends Shift+Enter to vim! Yes, the function key, like if I pressed Fn+F1 I mute the sound on my laptop. Even weirder, looking at the output from `xev`, xorg sees the keypad enter key (vs the regular return key) when the function key is pressed. So on my system, KP_Enter is the same as Shift+Return? :confounded: (OS: Arch linux, running kernel 4.7.4-1-ARCH, GNOME 3.20.2. The laptop is a DELL Latitude E5470.) What a weird little rabbit hole. :rabbit2:

**Comment by drmikehenry** [comment] 2016-09-21 10:38
I haven't been following the changes with the ``COLORTERM`` variable.  Some searching makes me think that gnome-terminal stopped setting it at all for a while, and now some are suggesting to set it to ``truecolor`` as is done on your system.  So Fixkey detects this terminal as XTerm, which is close enough to most terminals that it will generally work.  That's expected behavior for terminals that masquerade as a real XTerm by setting ``TERM=xterm``.

You might want to try the mappings suggested in fixkey.txt in section "3.9 Terminal testing":
```sh
vim '+runtime scripts/fixkeytest.vim'
```
Then you can enter insert mode and press lots of keys to see if they are set correctly.  I hadn't tested this before, but on my full-sized desktop keyboard I get the same behavior you do regarding Enter and Keypad Enter.  The keypad Enter key shows up as <S-Enter>, whereas pressing Shift+Enter still looks like Enter.

**Comment by drmikehenry** [comment] 2016-10-05 01:17
Since it looks like everything is working as expected, I'm closing this ticket.

**Closed by drmikehenry** 2016-10-05 01:17 UTC
